test. wait for Deploy job to complete

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -157,7 +157,8 @@ jobs:
   trigger-deploy:
 #    needs: publish-docker-image
     runs-on: ubuntu-22.04
-
+    outputs:
+      workflow_run_id: ${{ steps.get_run_id.workflow_run_id }}
     steps:
       # Шаг 1: Отправка события deploy
       - name: Trigger deploy event in my-calendar-docker-compose
@@ -174,29 +175,33 @@ jobs:
         run: |
           workflow_run_id=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
             https://api.github.com/repos/andreparkh/my-calendar-docker-compose/actions/runs | jq -r '.workflow_runs[0].id')
-          echo "get_run_id $workflow_run_id"
-      - name: Wait for Docker Job to Complete
-        run: |
-          WORKFLOW_RUN_ID=${{ steps.get_run_id.outputs.workflow_run_id }}
-          echo "WORKFLOW_RUN_ID = $WORKFLOW_RUN_ID"
-          while true; do
-            STATUS=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
-              https://api.github.com/repos/andreparkh/my-calendar-docker-compose/actions/runs/$WORKFLOW_RUN_ID | jq -r '.status')
-            echo "$STATUS"
-            if [ "$STATUS" == "completed" ]; then
-              CONCLUSION=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
-                https://api.github.com/repos/andreparkh/my-calendar-docker-compose/actions/runs/$WORKFLOW_RUN_ID | jq -r '.conclusion')
-              if [ "$CONCLUSION" == "success" ]; then
-                echo "Docker job completed successfully!"
-                exit 0
-              else
-                echo "Docker job failed!"
-                exit 1
-              fi
+
+  wait-for-deploy-complete:
+    needs: trigger-deploy
+    runs-on: ubuntu-latest
+    steps:
+    - name: Wait for Docker Job to Complete
+      run: |
+        WORKFLOW_RUN_ID=${{ needs.trigger-deploy.outputs.workflow_run_id }}
+        echo "WORKFLOW_RUN_ID = $WORKFLOW_RUN_ID"
+        while true; do
+          STATUS=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
+            https://api.github.com/repos/andreparkh/my-calendar-docker-compose/actions/runs/$WORKFLOW_RUN_ID | jq -r '.status')
+          echo "$STATUS"
+          if [ "$STATUS" == "completed" ]; then
+            CONCLUSION=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
+              https://api.github.com/repos/andreparkh/my-calendar-docker-compose/actions/runs/$WORKFLOW_RUN_ID | jq -r '.conclusion')
+            if [ "$CONCLUSION" == "success" ]; then
+              echo "Docker job completed successfully!"
+              exit 0
+            else
+              echo "Docker job failed!"
+              exit 1
             fi
-            echo "Waiting for Docker job to complete..."
-            sleep 10
-          done
+          fi
+          echo "Waiting for Docker job to complete..."
+          sleep 10
+        done
 
       # Шаг 2: Ожидание завершения события
 #      - name: Wait for deploy status
